# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebTechnology_Course', '0002_auto_20171017_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
        migrations.AddField(
            model_name='author',
            name='surname',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
