# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebTechnology_Course', '0003_auto_20171018_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название главы', max_length=128)),
                ('chapter_number', models.IntegerField()),
                ('upload_date', models.DateField(auto_now=True)),
                ('raw_html_text', models.CharField(max_length=262140)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='last_update',
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebTechnology_Course.Book'),
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='next_chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nextchapter', to='WebTechnology_Course.BookChapter'),
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='prev_chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prevchapter', to='WebTechnology_Course.BookChapter'),
        ),
    ]
