# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebTechnology_Course', '0004_auto_20171028_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookchapter',
            name='next_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nextchapter', to='WebTechnology_Course.BookChapter'),
        ),
        migrations.AlterField(
            model_name='bookchapter',
            name='prev_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prevchapter', to='WebTechnology_Course.BookChapter'),
        ),
    ]
